FROM node:16.14.2

WORKDIR /src

ENV PORT 4002
ENV DB_URI mongodb+srv://admin:Password1234@cluster0.qsdy4.mongodb.net/YouVerifyOrderService?retryWrites=true&w=majority
ENV AMQP_URL amqps://cocgytbv:M-7jh7OWH8wji54yHC1_P0edO9jc6q7g@moose.rmq.cloudamqp.com/cocgytbv
ENV PRODUCT_SERVICE_URL http://localhost:4001/v1/products
ENV PAYMENT_SERVICE_URL http://localhost:4003/v1/payments

COPY package.json /src/

RUN yarn install

COPY . /src

EXPOSE 4002

CMD ["node", "build/src/interface/http/server.js"]